# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{modulesPath, ...}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["uhci_hcd" "ehci_pci" "ata_piix" "ahci" "usb_storage" "sd_mod" "sr_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel" "wl"];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/51a85007-e6ad-4cfd-b883-12658399a359";
    fsType = "ext4";
  };
  fileSystems."/media" = {
    device = "/dev/disk/by-uuid/9714f412-e647-4553-abe6-ac1e6b70040f";
    fsType = "ext4";
  };

  swapDevices = [{device = "/dev/disk/by-uuid/ee96e61f-7b27-43d2-a996-b4816819a971";}];
}
