#!/bin/sh

icon() {
  [ "$STATUS" = "no" ] && echo "" || echo ""
}

toggle() {
  if [ "$STATUS" = "no" ]; then
    rfkill block all
    notify-send --urgency=normal -i airplane-mode-symbolic "Airplane Mode" "Airplane mode has been turned on!"
  else
    rfkill unblock all
    notify-send --urgency=normal -i airplane-mode-disabled-symbolic "Airplane Mode" "Airplane mode has been turned off!"
  fi
}

if [ "$1" = "toggle" ]; then
  toggle
else
  rfkill event | while read -r _; do
    STATUS="$(rfkill list | sed -n 2p | awk '{print $3}')"
    icon
  done
fi
