#!/usr/bin/env bash

total="$(free -h --si | rg Mem | awk '{print $2}')"
free -h --si -s 3 | rg --line-buffered Mem | while read -r line; do
  used=$(echo "$line" | awk '{print $3}')
  perc=$(awk -v used="$used" -v total="$total" 'BEGIN{print sprintf("%.f", used/total*100)}')

  echo '{"total": "'"$total"'", "used": "'"$used"'", "percent": '"$perc"'}'
done
